// SPDX-FileCopyrightText: 2026 daringwalker
// SPDX-License-Identifier: GPL-3.0-or-later

#include "breezetheme.h"

#include <QColor>
#include <QStandardPaths>

namespace {
struct ThemeColors {
    QColor window;
    QColor windowText;
    QColor view;
    QColor viewAlternate;
    QColor button;
    QColor inactiveText;
    QColor tooltip;
    QColor selection;
    QColor selectionAlternate;
    QColor selectedText;
    QColor link;
    QColor visitedLink;
    QColor disabledText;
    QColor light;
    QColor midlight;
    QColor mid;
    QColor dark;
    QColor shadow;
};

// Values mirror KDE's BreezeLight.colors and BreezeDark.colors. Roles which
// are generated by KColorScheme are kept as close supporting shades so the
// Fusion fallback remains coherent on desktops without the Breeze style.
ThemeColors colorsFor(BreezeTheme::Variant variant)
{
    if (variant == BreezeTheme::Variant::Dark) {
        return {
            QColor(32, 35, 38), QColor(252, 252, 252),
            QColor(20, 22, 24),
            QColor(29, 31, 34), QColor(41, 44, 48),
            QColor(161, 169, 177), QColor(41, 44, 48),
            QColor(61, 174, 233), QColor(30, 87, 116),
            QColor(252, 252, 252), QColor(29, 153, 243),
            QColor(155, 89, 182), QColor(111, 116, 122),
            QColor(77, 80, 84), QColor(52, 55, 59),
            QColor(69, 73, 78), QColor(20, 22, 24),
            QColor(0, 0, 0),
        };
    }

    return {
        QColor(239, 240, 241), QColor(35, 38, 41),
        QColor(255, 255, 255),
        QColor(247, 247, 247), QColor(252, 252, 252),
        QColor(112, 125, 138), QColor(247, 247, 247),
        QColor(61, 174, 233), QColor(163, 212, 250),
        QColor(255, 255, 255), QColor(41, 128, 185),
        QColor(155, 89, 182), QColor(145, 151, 157),
        QColor(255, 255, 255), QColor(247, 247, 247),
        QColor(189, 195, 199), QColor(112, 125, 138),
        QColor(35, 38, 41),
    };
}

void applyGroup(QPalette &palette,
                QPalette::ColorGroup group,
                const ThemeColors &colors,
                const QColor &text)
{
    palette.setColor(group, QPalette::Window, colors.window);
    palette.setColor(group, QPalette::WindowText, text);
    palette.setColor(group, QPalette::Base, colors.view);
    palette.setColor(group, QPalette::AlternateBase,
                     colors.viewAlternate);
    palette.setColor(group, QPalette::ToolTipBase, colors.tooltip);
    palette.setColor(group, QPalette::ToolTipText, text);
    palette.setColor(group, QPalette::Text, text);
    palette.setColor(group, QPalette::Button, colors.button);
    palette.setColor(group, QPalette::ButtonText, text);
    palette.setColor(group, QPalette::BrightText,
                     colors.selectedText);
    palette.setColor(group, QPalette::Highlight, colors.selection);
    palette.setColor(group, QPalette::HighlightedText,
                     colors.selectedText);
    palette.setColor(group, QPalette::Link, colors.link);
    palette.setColor(group, QPalette::LinkVisited,
                     colors.visitedLink);
    palette.setColor(group, QPalette::Light, colors.light);
    palette.setColor(group, QPalette::Midlight, colors.midlight);
    palette.setColor(group, QPalette::Mid, colors.mid);
    palette.setColor(group, QPalette::Dark, colors.dark);
    palette.setColor(group, QPalette::Shadow, colors.shadow);
    palette.setColor(group, QPalette::PlaceholderText,
                     colors.inactiveText);
    palette.setColor(group, QPalette::Accent, colors.selection);
}
}

QPalette BreezeTheme::palette(Variant variant)
{
    const ThemeColors colors = colorsFor(variant);
    QPalette result;
    applyGroup(result, QPalette::Active, colors,
               colors.windowText);
    applyGroup(result, QPalette::Inactive, colors,
               colors.windowText);
    applyGroup(result, QPalette::Disabled, colors,
               colors.disabledText);
    result.setColor(QPalette::Disabled, QPalette::Highlight,
                    colors.selectionAlternate);
    result.setColor(QPalette::Disabled,
                    QPalette::HighlightedText,
                    colors.disabledText);
    return result;
}

QString BreezeTheme::colorSchemePath(Variant variant)
{
    const QString fileName = variant == Variant::Dark
        ? QStringLiteral("BreezeDark.colors")
        : QStringLiteral("BreezeLight.colors");
    return QStandardPaths::locate(
        QStandardPaths::GenericDataLocation,
        QStringLiteral("color-schemes/%1").arg(fileName),
        QStandardPaths::LocateFile);
}

QString BreezeTheme::preferredStyleName(
    const QStringList &availableStyleNames,
    bool nativeStylesAvailable)
{
    if (nativeStylesAvailable) {
        for (const QString &styleName : availableStyleNames) {
            if (styleName.compare(QStringLiteral("Breeze"),
                                  Qt::CaseInsensitive) == 0) {
                return styleName;
            }
        }
    }
    return QStringLiteral("Fusion");
}
